---

# Install Vagrant
- name: Download Vagrant
  get_url: url=https://dl.bintray.com/mitchellh/vagrant/vagrant_{{ vagrant_version }}_{{ vagrant_arch }}.deb
           dest=/var/cache/apt/archives/vagrant_{{ vagrant_version }}_{{ vagrant_arch }}.deb
  when: >
    vagrant_installed.stat.exists == False
    or vagrant_current_version.stdout != "{{vagrant_version}}"
  tags: vagrant

- name: Install Vagrant
  apt: deb=/var/cache/apt/archives/vagrant_{{ vagrant_version }}_{{ vagrant_arch }}.deb state=installed
  when: >
    vagrant_installed.stat.exists == False
    or vagrant_current_version.stdout != "{{vagrant_version}}"
  tags: vagrant
